#!/usr/bin/env python3
"""Build a full-text search index for the published HTML walkthroughs.

The site's main search index (search.json) is generated by Jekyll/Liquid and
covers every page that has YAML front matter. The MATLAB-published walkthrough
HTML files under _pages/ have NO front matter, so Jekyll treats them as static
files and they never enter that index. This script indexes their full text so
site search can find them.

Output: search-extra.json at the repo root (served at /search-extra.json). The
search page fetches it alongside search.json and merges the two.

Run from the repo root whenever walkthroughs are re-published:

    python3 markdown_generator/build_search_extra.py

Standard library only; no dependencies.
"""

import html
import json
import os
import re
from html.parser import HTMLParser

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES_DIR = os.path.join(REPO_ROOT, "_pages")
OUTPUT = os.path.join(REPO_ROOT, "search-extra.json")

MAX_CONTENT_CHARS = 20000
EXCERPT_CHARS = 200
SKIP_TAGS = {"script", "style", "head"}


class TextExtractor(HTMLParser):
    """Collect visible text and the document title / first heading."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self._skip_depth = 0
        self._chunks = []
        self._title_parts = []
        self._h1_parts = []
        self._in_title = False
        self._in_h1 = False

    def handle_starttag(self, tag, attrs):
        if tag in SKIP_TAGS:
            self._skip_depth += 1
        elif tag == "title":
            self._in_title = True
        elif tag == "h1" and not self._h1_parts:
            self._in_h1 = True

    def handle_endtag(self, tag):
        if tag in SKIP_TAGS and self._skip_depth:
            self._skip_depth -= 1
        elif tag == "title":
            self._in_title = False
        elif tag == "h1":
            self._in_h1 = False

    def handle_data(self, data):
        if self._skip_depth:
            return
        if self._in_title:
            self._title_parts.append(data)
        if self._in_h1:
            self._h1_parts.append(data)
        self._chunks.append(data)

    @property
    def text(self):
        return normalize(" ".join(self._chunks))

    @property
    def title(self):
        return normalize("".join(self._title_parts)) or normalize("".join(self._h1_parts))


def normalize(text):
    return re.sub(r"\s+", " ", html.unescape(text)).strip()


def title_from_path(rel_path):
    stem = os.path.splitext(os.path.basename(rel_path))[0]
    return stem.replace("_", " ").strip()


def has_front_matter(path):
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        return fh.readline().strip() == "---"


def build():
    records = []
    for dirpath, _dirs, files in os.walk(PAGES_DIR):
        for name in sorted(files):
            if not name.lower().endswith(".html"):
                continue
            path = os.path.join(dirpath, name)
            if has_front_matter(path):
                continue  # already covered by the Liquid-generated search.json
            with open(path, "r", encoding="utf-8", errors="replace") as fh:
                raw = fh.read()
            parser = TextExtractor()
            try:
                parser.feed(raw)
            except Exception:
                pass
            content = parser.text[:MAX_CONTENT_CHARS]
            if not content:
                continue
            rel_path = os.path.relpath(path, REPO_ROOT).replace(os.sep, "/")
            records.append(
                {
                    "title": parser.title or title_from_path(rel_path),
                    "excerpt": content[:EXCERPT_CHARS],
                    "category": "",
                    "tags": "walkthrough",
                    "url": "/" + rel_path,
                    "content": content,
                }
            )
    records.sort(key=lambda r: r["url"])
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        json.dump(records, fh, ensure_ascii=False, indent=1)
        fh.write("\n")
    print(f"Wrote {len(records)} records to {os.path.relpath(OUTPUT, REPO_ROOT)}")


if __name__ == "__main__":
    build()
